default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wan_weight_development

test:
  <<: *default
  database: wan_weight_test
  username: <%= ENV['DB_USERNAME'] || 'yukokawabata' %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>

production:
  <<: *default
  database: wan_weight_production
  username: wan_weight
  password: <%= ENV["WAN_WEIGHT_DATABASE_PASSWORD"] %>
