name: WanWeight GitHub Actions

on: [pull_request]

jobs:
  Job-Rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Rubocop
      run: bundle exec rubocop

  Job-RSpec:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wan_weight_test
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Precompile assets
      run: |
        RAILS_ENV=test bundle exec rails assets:precompile

    - name: Set up database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
      run: |
        bin/rails db:create db:schema:load RAILS_ENV=test

    - name: Run RSpec
      run: bundle exec rspec

  Job-Heroku-Deploy:
    runs-on: ubuntu-latest
    needs: [Job-RSpec]

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
